'use client'

import { ChevronDown } from 'lucide-react'
import { useState } from 'react'

import { CornerDiamonds } from '@/components/ui/intersection-diamonds'
import { cn } from '@/lib/utils'

type FaqItem = { question: string; answer: string }

const DEFAULT_FAQ_ITEMS: FaqItem[] = [
  {
    question: 'What is Generative Engine Optimization (GEO)?',
    answer:
      "Generative Engine Optimization is the practice of preparing a website's content, structure, and trust signals so that AI engines like ChatGPT, Claude, Gemini, and Perplexity understand the page, treat it as authoritative, and cite it in their generated answers. Signalor scores GEO across six pillars: content, schema, E-E-A-T, technical, entity, and AI visibility.",
  },
  {
    question: 'What is the difference between SEO and GEO?',
    answer:
      'Classic SEO targets the ten blue links of a search results page. GEO targets the answer text generated by an LLM, it requires answer-shaped content, complete Schema.org markup, strong entity signals, and verifiable trust markers so the model is willing to cite the source. Both still matter, but the optimization tactics differ.',
  },
  {
    question: 'Which AI engines does Signalor track?',
    answer:
      'Signalor tracks brand presence and citations across ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), Perplexity, Google AI Overviews, and Microsoft Copilot. Engine coverage varies by plan, the Max plan includes all engines.',
  },
  {
    question: 'How do I get started with Signalor?',
    answer:
      "Paste any public URL into the free analyzer at signalor.ai. You'll get a GEO score, citation signals, and a prioritized fix list, no install required. Create an account when you want to save runs and track changes over time.",
  },
  {
    question: 'How does Signalor score a website?',
    answer:
      'Six weighted pillars: content (0.20), schema (0.15), E-E-A-T (0.20), technical (0.15), entity (0.15), and AI visibility (0.15). Each pillar rolls 5-15 sub-checks into a 0-100 score; the weighted average is the final GEO score, with prioritized fixes attached to each pillar.',
  },
  {
    question: 'Does Signalor work with Shopify and WordPress?',
    answer:
      'Yes. Signalor offers a Shopify integration that scores product and content pages, and a self-hosted WordPress plugin (signalor-geo) that surfaces recommendations and applies one-click schema fixes inside the WordPress admin.',
  },
]

interface FaqProps {
  sectionId?: string
  headingId?: string
  heading?: string
  description?: string
  items?: FaqItem[]
}

export function Faq({
  sectionId = 'faq',
  headingId = 'landing-faq-heading',
  heading = 'FAQs',
  description = 'Get answers to the most common questions about AI search and Signalor.',
  items = DEFAULT_FAQ_ITEMS,
}: FaqProps): JSX.Element {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  return (
    <section
      id={sectionId}
      className="bg-muted relative border-t border-black/8 px-6 py-20 sm:py-24 lg:px-12"
      aria-labelledby={headingId}
    >
      <CornerDiamonds top />
      <div className="mx-auto max-w-3xl text-center">
        <h2
          id={headingId}
          className="text-foreground font-sans text-4xl font-bold tracking-tight sm:text-5xl"
        >
          {heading}
        </h2>
        <p className="text-muted-foreground mx-auto mt-4 max-w-xl text-base leading-relaxed font-normal sm:text-lg">
          {description}
        </p>
      </div>

      <div className="mx-auto mt-12 max-w-3xl">
        <ul className="border-t border-black/10">
          {items.map((item, index) => {
            const isOpen = openIndex === index
            const panelId = `faq-panel-${index}`
            const buttonId = `faq-trigger-${index}`
            return (
              <li key={item.question} className="border-b border-black/10">
                <h3 className="text-foreground m-0 text-base leading-snug font-medium">
                  <button
                    id={buttonId}
                    type="button"
                    aria-expanded={isOpen}
                    aria-controls={panelId}
                    className="hover:text-foreground/90 flex w-full items-center justify-between gap-4 py-5 text-left transition-colors sm:py-6"
                    onClick={() => setOpenIndex(isOpen ? null : index)}
                  >
                    <span className="min-w-0 pr-2">{item.question}</span>
                    <ChevronDown
                      className={cn(
                        'text-muted-foreground h-5 w-5 shrink-0 transition-transform duration-200',
                        isOpen && 'rotate-180',
                      )}
                      aria-hidden
                    />
                  </button>
                </h3>
                <div
                  id={panelId}
                  role="region"
                  aria-labelledby={buttonId}
                  className={cn(
                    'grid transition-[grid-template-rows] duration-200 ease-out',
                    isOpen ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]',
                  )}
                >
                  <div className="min-h-0 overflow-hidden">
                    <p className="text-muted-foreground pr-10 pb-5 text-sm leading-relaxed">
                      {item.answer}
                    </p>
                  </div>
                </div>
              </li>
            )
          })}
        </ul>
      </div>
    </section>
  )
}
