import type { Metadata } from 'next'

import { LandingNav } from '@/features/landing/components/LandingNav'

import { JsonLd } from '@/features/site/components/seo/json-ld'
import {
  AGGREGATE_RATING,
  breadcrumbJsonLd,
  buildMetadata,
  faqJsonLd,
  SITE_BRAND,
  SITE_URL,
} from '@/features/site/lib/seo'
import { HomeCta } from '@/features/site/components/landing/home-cta'
import { HomeFaq } from '@/features/site/components/landing/home-faq'
import { HomeFeatureShowcase } from '@/features/site/components/landing/home-feature-showcase'
import { HomeFeatures } from '@/features/site/components/landing/home-features'
import { HomeHero } from '@/features/site/components/landing/home-hero'
import { HomeHowItWorks } from '@/features/site/components/landing/home-how-it-works'
import { HomeIntegrations } from '@/features/site/components/landing/home-integrations'
import { HomeLogoCloud } from '@/features/site/components/landing/home-logo-cloud'
import { HomePricing } from '@/features/site/components/landing/home-pricing'
import { HomeStats } from '@/features/site/components/landing/home-stats'
import { HomeFooter } from '@/features/site/components/landing/home-footer'
import { HomeTestimonials } from '@/features/site/components/landing/home-testimonials'

const HOMEPAGE_FAQ = [
  {
    question: 'What is Generative Engine Optimization (GEO)?',
    answer:
      "Generative Engine Optimization is the practice of preparing a website's content, structure, and trust signals so that AI engines like ChatGPT, Claude, Gemini, and Perplexity understand the page, treat it as authoritative, and cite it in their generated answers. SignalorAI scores GEO across six pillars: content, schema, E-E-A-T, technical, entity, and AI visibility.",
  },
  {
    question: 'What is the difference between SEO and GEO?',
    answer:
      'Classic SEO targets the ten blue links of a search results page. GEO targets the answer text generated by an LLM, it requires answer-shaped content, complete Schema.org markup, strong entity signals, and verifiable trust markers so the model is willing to cite the source. Both still matter, but the optimization tactics differ.',
  },
  {
    question: 'Which AI engines does SignalorAI track?',
    answer:
      'SignalorAI tracks brand presence and citations across ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), Perplexity, Google AI Overviews, and Microsoft Copilot. Engine coverage varies by plan, the Max plan includes all engines.',
  },
  {
    question: 'How do I get started with SignalorAI?',
    answer:
      "Paste any public URL into the free analyzer at signalor.ai. You'll get a GEO score, citation signals, and a prioritized fix list, no install required. Create an account when you want to save runs and track changes over time.",
  },
  {
    question: 'How does SignalorAI score a website?',
    answer:
      'Six weighted pillars: content (0.20), schema (0.15), E-E-A-T (0.20), technical (0.15), entity (0.15), and AI visibility (0.15). Each pillar rolls 5-15 sub-checks into a 0-100 score; the weighted average is the final GEO score, with prioritized fixes attached to each pillar.',
  },
  {
    question: 'Does SignalorAI work with Shopify and WordPress?',
    answer:
      'Yes. SignalorAI offers a Shopify integration that scores product and content pages, and a self-hosted WordPress plugin (signalor-geo) that surfaces recommendations and applies one-click schema fixes inside the WordPress admin.',
  },
]

export const metadata: Metadata = {
  ...buildMetadata({
    description:
      'SignalorAI scores, monitors, and improves how ChatGPT, Claude, Gemini, Perplexity, and Google AI cite your brand. Free GEO + AEO audit, paste any URL to start.',
    path: '/',
  }),
  // Absolute title bypasses the root "%s | SignalorAI" template so the brand
  // leads the SERP (helps the brand-term ranking) without a redundant suffix.
  title: { absolute: 'SignalorAI | AI Visibility & GEO Platform for AI Search' },
}

const homeProductJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Product',
  name: SITE_BRAND,
  description:
    'GEO and AEO platform that scores how AI engines cite your brand and ships prioritized fixes.',
  brand: { '@type': 'Brand', name: 'SignalorAI' },
  url: SITE_URL,
  image: `${SITE_URL}/icon.svg`,
  offers: {
    '@type': 'AggregateOffer',
    priceCurrency: 'GBP',
    lowPrice: '0',
    highPrice: '99.69',
    offerCount: 3,
    url: `${SITE_URL}/pricing`,
  },
  aggregateRating: AGGREGATE_RATING,
}

export default function HomePage(): JSX.Element {
  return (
    <div className="min-h-screen overflow-x-clip bg-[#fafafa] font-sans">
      <JsonLd id="ld-home-breadcrumb" data={breadcrumbJsonLd([{ name: 'Home', path: '/' }])} />
      <JsonLd id="ld-home-faq" data={faqJsonLd(HOMEPAGE_FAQ)} />
      <JsonLd id="ld-home-product" data={homeProductJsonLd} />

      <header className="border-border border-b">
        <div className="border-border mx-auto max-w-6xl border-x">
          <LandingNav />
        </div>
      </header>
      <main>
        <HomeHero />
        <div className="border-border mx-auto max-w-6xl border-x">
          <HomeLogoCloud />
          <HomeFeatures />
          <HomeFeatureShowcase />
          <HomeHowItWorks />
          <HomeStats />
          <HomeTestimonials />
          <HomeIntegrations />
          <HomePricing />
          <HomeFaq items={HOMEPAGE_FAQ} />
        </div>
        <HomeCta />
      </main>
      <HomeFooter />
    </div>
  )
}
