import { AnnouncementBar } from '@/features/landing/components/AnnouncementBar'
import { Faq } from '@/features/landing/components/Faq'
import { FeaturesGrid } from '@/features/landing/components/FeaturesGrid'
import { Footer } from '@/features/landing/components/Footer'
import { Hero } from '@/features/landing/components/Hero'
import { HowItWorks } from '@/features/landing/components/HowItWorks'
import { IntegrationsStrip } from '@/features/landing/components/IntegrationsStrip'
import { LandingNav } from '@/features/landing/components/LandingNav'
import { Newsletter } from '@/features/landing/components/Newsletter'
import { PricingTeaser } from '@/features/landing/components/PricingTeaser'
import { Testimonials } from '@/features/landing/components/Testimonials'
import { WhySignalor } from '@/features/landing/components/WhySignalor'

const HOMEPAGE_FAQ = [
  {
    question: 'What is Generative Engine Optimization (GEO)?',
    answer:
      "Generative Engine Optimization is the practice of preparing a website's content, structure, and trust signals so that AI engines like ChatGPT, Claude, Gemini, and Perplexity understand the page, treat it as authoritative, and cite it in their generated answers. Signalor scores GEO across six pillars: content, schema, E-E-A-T, technical, entity, and AI visibility.",
  },
  {
    question: 'What is the difference between SEO and GEO?',
    answer:
      'Classic SEO targets the ten blue links of a search results page. GEO targets the answer text generated by an LLM, it requires answer-shaped content, complete Schema.org markup, strong entity signals, and verifiable trust markers so the model is willing to cite the source. Both still matter, but the optimization tactics differ.',
  },
  {
    question: 'Which AI engines does Signalor track?',
    answer:
      'Signalor tracks brand presence and citations across ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), Perplexity, Google AI Overviews, and Microsoft Copilot. Engine coverage varies by plan, the Max plan includes all engines.',
  },
  {
    question: 'How do I get started with Signalor?',
    answer:
      "Paste any public URL into the free analyzer at signalor.ai. You'll get a GEO score, citation signals, and a prioritized fix list, no install required. Create an account when you want to save runs and track changes over time.",
  },
  {
    question: 'How does Signalor score a website?',
    answer:
      'Six weighted pillars: content (0.20), schema (0.15), E-E-A-T (0.20), technical (0.15), entity (0.15), and AI visibility (0.15). Each pillar rolls 5-15 sub-checks into a 0-100 score; the weighted average is the final GEO score, with prioritized fixes attached to each pillar.',
  },
  {
    question: 'Does Signalor work with Shopify and WordPress?',
    answer:
      'Yes. Signalor offers a Shopify integration that scores product and content pages, and a self-hosted WordPress plugin (signalor-geo) that surfaces recommendations and applies one-click schema fixes inside the WordPress admin.',
  },
]

export default function HomePage(): JSX.Element {
  return (
    <div className="min-h-screen overflow-x-clip bg-[#fbfbfa] font-sans">
      {/* new-signalor header + hero — gradient spans from the very top */}
      <div className="relative overflow-hidden">
        <div className="hero-aurora pointer-events-none absolute inset-0 opacity-60" />
        <div className="hero-grain pointer-events-none absolute inset-0" />
        <div className="relative z-10">
          <AnnouncementBar />
          <LandingNav />
          <Hero />
        </div>
      </div>

      {/* the rest of the landing — ranking-fe sections */}
      <HowItWorks />
      <FeaturesGrid />
      <Testimonials />
      <WhySignalor />
      <IntegrationsStrip />
      <PricingTeaser />
      <Faq items={HOMEPAGE_FAQ} />
      <Newsletter />
      <Footer />
    </div>
  )
}
